### PR TITLE
docs: Add Easypanel as a deployment method

### PR DESCRIPTION
**Pull request by berksmbl**
1-click installation for EasyPanel

### CODE REVIEW

**Comment by advplyr** [comment]
It looks like the version of Abs from this is a few months out of date. Are you the author of that?

**Comment by berksmbl** [comment]
> It looks like the version of Abs from this is a few months out of date. Are you the author of that?

Schemas can be created and updated by the community. I just sent an update [request ](https://github.com/easypanel-io/templates/pull/377)and it will be updated soon.

**Comment by berksmbl** [comment]
@advplyr Hello, I'm writing because I haven't received an answer for a long time.

**Comment by advplyr** [comment]
Hey, I was going to look into this Easypanel since I never heard of it but then I forgot. I don't have time to check it out so will just put this in for now

**Pull request merged**
