### PR TITLE
CSS Updates

### LINKED ISSUE #69: Improve UI
While the guides and docs on the website just keep getting better and better, It seems like multiple aspects of the UI is in need of some smoothing out. Problems seem most notable in the nav bar, which is jarringly inconsistent between pages and sometimes non-existent. This seems especially problematic when page links move from the left side of the screen to the right and are added/removed/change their names. You can usually get where you need to go, but having four different systems of navigation within as many clicks of each other doesn't seem very user-friendly. Additionally, the FAQ tab is only visible on the docs or the guides page, and isn't even present on the navbar when you are in the FAQ tab itself. On small screens, the sidebar also disappears which mades navigation through guides impossible as brought up in #28, and the showcase tab disappears entirely.

All just CSS nitpicking, but still worth addressing.

<details>
<summary>Screenshots</summary>

Bottom right navigation:
Screenshot 2023-12-29 at 12 00 00 AM

Top right navigation
Screenshot 2023-12-29 at 12 00 12 AM

Top left navigation
Screenshot 2023-12-29 at 12 00 25 AM

Mobile shortened navigation:
Screenshot 2023-12-29 at 12 00 45 AM

Mobile guides:
Screenshot 2023-12-29 at 12 00 55 AM

</details>

### PR DESCRIPTION
**Pull request by nichwall**
Fixes #69 

~~Still working on getting the FAQ page fixed.~~
Not sure these changes are the best way to do things, but they seem to work.

### CODE REVIEW

**Comment by nichwall** [comment]
Okay, actually the last commit. Was cleaning up some old files.

**Comment by advplyr** [comment]
We shouldn't delete the privacy policy even if it isn't linked in the website anywhere because I have to put a privacy policy link in app store releases

**Comment by nichwall** [comment]
Ah, okay. Thanks for clarify, I had moved it into the General FAQ as a question, but it can remain as a separate page.

**Comment by advplyr** [comment]
We don't need it in the FAQ actually. The only reason I had it as a page was to link to for app stores.

**Comment by nichwall** [comment]
Ah, okay. I can roll that change back, but it'll be a bit before I'm able to do it if you want to do it now.

**Comment by nichwall** [comment]
The privacy policy commit has been rolled back.

**Comment by advplyr** [comment]
I added a drawer for mobile and added a package `v-click-outside` so you will need to do another `npm install` once you pull this.

Looks good, thanks!

**Pull request merged**
