### PR TITLE
Add nix installation instructions

### PR DESCRIPTION
**Pull request by jvanbruegge**
I've packaged audiobookshelf for the nix package manager: https://github.com/NixOS/nixpkgs/pull/213265

I would merge this once the PR hits nixos-unstable in a few days: https://nixpk.gs/pr-tracker.html?pr=213265

### CODE REVIEW

**Comment by jvanbruegge** [comment]
It is not in unstable, so ready to merge

**Comment by advplyr** [comment]
Awesome, thanks. How will this install method be keeping up with releases?

**Comment by jvanbruegge** [comment]
I have enabled notifications for new github releases so I can bump the version number and hashes like here: https://github.com/NixOS/nixpkgs/pull/225296

But even if that takes a while to get merged, the nice thing about nix is that you can easily overwrite single packages, so if a users wants to use the newest version they can either check out the fork and install from there (in case I already made a PR) or do the hash overrides locally using `overwriteAttrs`

**Comment by advplyr** [comment]
How long do version update PRs usually take to merge? All the packages on nix have to be manually updated in that way?

**Comment by jvanbruegge** [comment]
One to two weeks usually, sometimes much faster. For packages that can be updated automatically there is a bot creating the PRs, but i think that it does not work for npm packages at the moment, so yes the PRs are made manually.

**Comment by advplyr** [comment]
Sounds good. There may still be breaking changes in the future for the mobile apps.
Thanks for putting Abs on Nix!

**Pull request merged**
